# Generated by Django 6.0.2 on 2026-08-08 21:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_agences/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Hajj 2027, Omra Ramadan 2027', max_length=255)),
                ('type_voyage', models.CharField(choices=[('hajj', 'Hajj'), ('omra', 'Omra')], max_length=10)),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField()),
                ('nb_places_max', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='core.agence')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['-date_depart'],
            },
        ),
        migrations.CreateModel(
            name='Pelerin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1, null=True)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('statut_dossier', models.CharField(choices=[('incomplet', 'Incomplet'), ('complet', 'Complet'), ('valide', 'Validé')], default='incomplet', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelerins', to='core.groupe')),
            ],
            options={
                'verbose_name': 'Pèlerin',
                'verbose_name_plural': 'Pèlerins',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('passeport', 'Passeport'), ('visa', 'Visa'), ('certificat_vaccination', 'Certificat de vaccination'), ('photo', "Photo d'identité"), ('autre', 'Autre')], max_length=30)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents_pelerins/')),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('manquant', 'Manquant'), ('soumis', 'Soumis'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='manquant', max_length=20)),
                ('date_upload', models.DateTimeField(blank=True, null=True)),
                ('pelerin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.pelerin')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['type_document'],
                'unique_together': {('pelerin', 'type_document')},
            },
        ),
        migrations.CreateModel(
            name='PlanPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('nombre_tranches', models.PositiveSmallIntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('pelerin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_paiement', to='core.pelerin')),
            ],
            options={
                'verbose_name': 'Plan de paiement',
                'verbose_name_plural': 'Plans de paiement',
            },
        ),
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tranche', models.PositiveSmallIntegerField()),
                ('montant_prevu', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('payee', 'Payée'), ('partielle', 'Partiellement payée'), ('en_retard', 'En retard')], default='a_venir', max_length=20)),
                ('plan_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='core.planpaiement')),
            ],
            options={
                'verbose_name': 'Tranche',
                'verbose_name_plural': 'Tranches',
                'ordering': ['numero_tranche'],
                'unique_together': {('plan_paiement', 'numero_tranche')},
            },
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=10)),
                ('date_envoi_prevue', models.DateTimeField()),
                ('date_envoi_reelle', models.DateTimeField(blank=True, null=True)),
                ('statut_envoi', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('echec', 'Échec')], default='en_attente', max_length=20)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='core.document')),
                ('tranche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='core.tranche')),
            ],
            options={
                'verbose_name': 'Rappel',
                'verbose_name_plural': 'Rappels',
                'ordering': ['-date_envoi_prevue'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('gerant', 'Gérant'), ('agent', 'Agent commercial')], default='agent', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='core.agence')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('virement', 'Virement bancaire'), ('autre', 'Autre')], default='especes', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('tranche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.tranche')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
