# Generated by Django 6.0.2 on 2026-08-08 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='compte',
            field=models.OneToOneField(blank=True, help_text='Compte Django lié à cet utilisateur métier (clé du multi-tenant).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_agence', to=settings.AUTH_USER_MODEL),
        ),
    ]
